#! /bin/sh
# chkconfig: 2345 85 15
### BEGIN INIT INFO
# description: ZRY Center Logging System Server
# processname: zlogsysd
# pidfile: /dev/shm/zlogsysd.pid
### END INIT INFO
start(){
    python2.7 /home/wwwcgi/zlogsysd/zlogsysd.py start
}
stop(){
    python2.7 /home/wwwcgi/zlogsysd/zlogsysd.py stop
}
restart(){
    python2.7 /home/wwwcgi/zlogsysd/zlogsysd.py restart
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
esac
exit 0
