#! /bin/sh
# chkconfig: 2345 85 15
### BEGIN INIT INFO
# description: ZRY Center Logging System Server
# processname: zlogsysd
# pidfile: /dev/shm/zlogsysd.pid
### END INIT INFO

export basedir=/home/wwwcgi/zlogsysd/
export pidfile=/run/zlogsysd.pid
export webhost=0.0.0.0
export webport=9564
export sysloghost=0.0.0.0
export syslogport=9514
export proccessMonitorOn=False

start(){
	cd ${basedir}
	touch ${basedir}zlogsysd.out.log
	touch ${basedir}zlogsysd.err.log
    python ${basedir}zlogsysd.py start
}
stop(){
	cd ${basedir}
    python ${basedir}zlogsysd.py stop
}
restart(){
	cd ${basedir}
    python ${basedir}zlogsysd.py stop
    python ${basedir}zlogsysd.py start
}
syncdb(){
	if [ "$#" -eq "1" ]
	    cd ${basedir}
        python ${basedir}zlogsysd.py syncdb
    fi
    if [ "$#" -eq "2" ]
    	cd ${basedir}
        python ${basedir}zlogsysd.py syncdb $2
    fi
}
redeploy(){
  cd ${basedir}
  python ${basedir}zlogsysd.py stop
  echo -e "[\033[40;33mUsage:Pulling Code From Git............\033[0m]"
  git reset --hard origin/master
  git clean -f
  git pull
  git checkout master
  python ${basedir}zlogsysd.py start
}
pulldev(){
  cd ${basedir}
  python ${basedir}zlogsysd.py stop
  echo -e "[\033[40;33mUsage:Pulling Code From Git............\033[0m]"
  git reset --hard origin/dev
  git clean -f
  git pull
  git checkout dev
  python ${basedir}zlogsysd.py start
}
case "$1" in
start)
start
;;
stop)
stop
;;
restart)
restart
;;
redeploy)
redeploy
;;
pulldev)
pulldev
;;
syncdb)
syncdb
;;
*)
echo -e "[\033[40;31mInvalid Command.\033[0m]"
echo -e "[\033[40;33mUsage:\033[0m] zlogsysd start|stop|restart|redeploy|syncdb|pulldev"
esac
exit 0

